#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
  path:       /login
  controller: App\Controller\SecurityController::login
  methods: GET|POST

# app/config/routing.yml
#facebook_login:
 # path: /login/check-facebook

#hwi_oauth_redirect:
 # resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
  #prefix:   /connect

#hwi_oauth_connect:
 # resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
  #prefix:   /connect

#hwi_oauth_login:
 # resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
  #prefix:   /login